from __future__ import annotations

import json
import time
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from threading import Thread
from typing import Any, Callable

from packages.contributions.games.ai_playtest_execution import (
    AI_PLAYTEST_EXECUTION_PACKET_SCHEMA,
    evaluate_ai_playtest_execution_packet,
)
from packages.contributions.games.ai_playtest_lab import AI_PLAYTEST_MODES, AI_PLAYTEST_PLAN_SCHEMA


AI_PLAYTEST_RUN_SCHEMA = "universal_ai_playtest_runner_v1"
BrowserRunner = Callable[[dict[str, Any], Path], dict[str, Any]]


def run_ai_playtest_plan(
    *,
    plan: dict[str, Any],
    workspace_root: str | Path,
    output_dir: str | Path,
    target_url: str | None = None,
    build_output_path: str | Path | None = None,
    engine_native_product_body: dict[str, Any] | None = None,
    quality_overrides: dict[str, Any] | None = None,
    browser_runner: BrowserRunner | None = None,
    require_artifact_files: bool = True,
) -> dict[str, Any]:
    """Run a browser-backed AI playtest pass and produce a gate-ready packet.

    The runner intentionally stays conservative: browser smoke evidence can
    prove fresh artifacts and runtime errors, but it cannot fabricate subjective
    polish, core-loop, or requirement-fidelity GO. Those higher-level judgments
    must come from explicit quality overrides generated by a review/AI stage.
    """

    root = Path(workspace_root).resolve()
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    resolved_plan = plan if isinstance(plan, dict) else {}
    quality = quality_overrides if isinstance(quality_overrides, dict) else {}
    browser_result = _run_browser_layer(
        plan=resolved_plan,
        output_dir=out,
        target_url=target_url,
        build_output_path=build_output_path,
        browser_runner=browser_runner,
    )
    packet = _build_execution_packet(
        plan=resolved_plan,
        output_dir=out,
        browser_result=browser_result,
        quality_overrides=quality,
        engine_native_product_body=engine_native_product_body,
    )
    packet_path = out / "ai_playtest_execution_packet.json"
    packet_path.write_text(json.dumps(packet, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    report = evaluate_ai_playtest_execution_packet(
        packet,
        workspace_root=root,
        require_artifact_files=require_artifact_files,
    )
    report["runner"] = {
        "schema_version": AI_PLAYTEST_RUN_SCHEMA,
        "browser_runner_go": bool(browser_result.get("go")),
        "browser_runner_blockers": list(browser_result.get("blockers") or []),
        "packet_path": packet_path.as_posix(),
    }
    report_path = out / "ai_playtest_execution_report.json"
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return {
        "schema_version": AI_PLAYTEST_RUN_SCHEMA,
        "go": bool(report.get("go")),
        "packet": packet,
        "report": report,
        "packet_path": packet_path.as_posix(),
        "report_path": report_path.as_posix(),
        "browser_result": browser_result,
    }


def _run_browser_layer(
    *,
    plan: dict[str, Any],
    output_dir: Path,
    target_url: str | None,
    build_output_path: str | Path | None,
    browser_runner: BrowserRunner | None,
) -> dict[str, Any]:
    context = {
        "plan": plan,
        "target_url": target_url,
        "build_output_path": str(build_output_path) if build_output_path is not None else None,
    }
    if browser_runner is not None:
        return browser_runner(context, output_dir)
    if not target_url and build_output_path is None:
        return {
            "go": False,
            "blockers": ["ai_playtest_browser_target_missing"],
            "screenshots": [],
            "console_errors": [],
            "page_errors": [],
            "device_results": [],
            "performance_metrics": {},
        }
    try:
        return _run_playwright_browser_smoke(
            target_url=target_url,
            build_output_path=Path(build_output_path).resolve() if build_output_path is not None else None,
            output_dir=output_dir,
        )
    except Exception as exc:
        return {
            "go": False,
            "blockers": [f"ai_playtest_browser_runner_{type(exc).__name__}"],
            "error": str(exc),
            "screenshots": [],
            "console_errors": [],
            "page_errors": [],
            "device_results": [],
            "performance_metrics": {},
        }


def _build_execution_packet(
    *,
    plan: dict[str, Any],
    output_dir: Path,
    browser_result: dict[str, Any],
    quality_overrides: dict[str, Any],
    engine_native_product_body: dict[str, Any] | None,
) -> dict[str, Any]:
    mode_results: dict[str, dict[str, Any]] = {}
    browser_go = bool(browser_result.get("go"))
    browser_blockers = [str(item) for item in browser_result.get("blockers") or [] if str(item).strip()]
    screenshots = [str(item) for item in browser_result.get("screenshots") or [] if str(item).strip()]
    console_errors = [str(item) for item in browser_result.get("console_errors") or [] if str(item).strip()]
    page_errors = [str(item) for item in browser_result.get("page_errors") or [] if str(item).strip()]
    for mode in AI_PLAYTEST_MODES:
        replay_path = output_dir / "replays" / f"{mode}.jsonl"
        state_path = output_dir / "states" / f"{mode}.json"
        replay_path.parent.mkdir(parents=True, exist_ok=True)
        state_path.parent.mkdir(parents=True, exist_ok=True)
        replay_path.write_text(
            json.dumps(
                {
                    "mode": mode,
                    "event": "browser_smoke_replay",
                    "browser_go": browser_go,
                    "blockers": browser_blockers,
                    "created_at_ms": int(time.time() * 1000),
                },
                ensure_ascii=False,
            )
            + "\n",
            encoding="utf-8",
        )
        state_path.write_text(
            json.dumps(
                {
                    "mode": mode,
                    "browser_go": browser_go,
                    "target_url": browser_result.get("url"),
                    "screenshot_count": len(screenshots),
                },
                ensure_ascii=False,
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        mode_results[mode] = {
            "status": "completed" if browser_go else "blocked",
            "fresh_run": browser_go,
            "replay_artifacts": [replay_path.as_posix()] if browser_go else [],
            "screenshots": screenshots,
            "state_snapshots": [state_path.as_posix()] if browser_go else [],
            "findings": _mode_findings(mode, browser_blockers),
            "console_errors": console_errors,
            "page_errors": page_errors,
        }
    scripted_scenarios = _string_list(plan.get("scripted_scenarios"))
    device_results = browser_result.get("device_results") if isinstance(browser_result.get("device_results"), list) else []
    vision_targets = _string_list(plan.get("vision_review_targets"))
    vision_review = quality_overrides.get("vision_review") if isinstance(quality_overrides.get("vision_review"), dict) else {}
    return {
        "schema_version": AI_PLAYTEST_EXECUTION_PACKET_SCHEMA,
        "plan": plan,
        "workflow_generated_product_go": bool(quality_overrides.get("workflow_generated_product_go")),
        "core_loop_playable": bool(quality_overrides.get("core_loop_playable")),
        "first_session_flow_go": bool(quality_overrides.get("first_session_flow_go")),
        "requirement_fidelity_go": bool(quality_overrides.get("requirement_fidelity_go")),
        "area_scores": quality_overrides.get("area_scores") if isinstance(quality_overrides.get("area_scores"), dict) else {},
        "mode_results": mode_results,
        "scripted_scenario_results": [
            {"scenario": scenario, "status": "passed" if browser_go and not browser_blockers else "blocked"}
            for scenario in scripted_scenarios
        ],
        "state_assertion_results": [
            {"assertion": assertion, "status": "passed" if browser_go and not browser_blockers else "blocked"}
            for assertion in _string_list(plan.get("state_assertions"))
        ],
        "device_matrix_results": device_results,
        "performance_metrics": browser_result.get("performance_metrics") if isinstance(browser_result.get("performance_metrics"), dict) else {},
        "vision_review": {
            "visual_go": bool(vision_review.get("visual_go")),
            "targets_checked": _string_list(vision_review.get("targets_checked")),
            "blockers": _string_list(vision_review.get("blockers"))
            or ([] if vision_review.get("visual_go") else ["vision_review_requires_ai_or_human_annotation"]),
            "screenshots": screenshots,
        },
        "engine_native_product_body": engine_native_product_body or quality_overrides.get("engine_native_product_body"),
        "omitted_requirement_ids": _string_list(quality_overrides.get("omitted_requirement_ids")),
        "placeholder_only": bool(quality_overrides.get("placeholder_only")),
        "stale_evidence_reused": False,
    }


def _mode_findings(mode: str, blockers: list[str]) -> list[dict[str, Any]]:
    return [
        {
            "finding_id": f"{mode}_{blocker}",
            "severity": "P1",
            "category": "robustness",
            "observed": blocker,
        }
        for blocker in blockers
    ]


class _QuietHandler(SimpleHTTPRequestHandler):
    def log_message(self, format: str, *args: Any) -> None:
        return


def _serve_directory(directory: Path) -> tuple[ThreadingHTTPServer, int]:
    class Handler(_QuietHandler):
        def __init__(self, *args: Any, **kwargs: Any) -> None:
            super().__init__(*args, directory=str(directory), **kwargs)

    server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
    thread = Thread(target=server.serve_forever, daemon=True)
    thread.start()
    return server, int(server.server_address[1])


def _run_playwright_browser_smoke(
    *,
    target_url: str | None,
    build_output_path: Path | None,
    output_dir: Path,
) -> dict[str, Any]:
    from playwright.sync_api import sync_playwright

    server: ThreadingHTTPServer | None = None
    if target_url:
        url = target_url
    else:
        if build_output_path is None:
            raise ValueError("target_url_or_build_output_path_required")
        server, port = _serve_directory(build_output_path)
        url = f"http://127.0.0.1:{port}/index.html"
    screenshots: list[str] = []
    console_errors: list[str] = []
    page_errors: list[str] = []
    device_results: list[dict[str, Any]] = []
    started = time.perf_counter()
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            for name, viewport, is_mobile in (
                ("desktop", {"width": 1280, "height": 720}, False),
                ("mobile_portrait", {"width": 390, "height": 844}, True),
            ):
                page = browser.new_page(viewport=viewport, is_mobile=is_mobile, has_touch=is_mobile)
                page.on("console", lambda msg: console_errors.append(msg.text) if msg.type == "error" else None)
                page.on("pageerror", lambda exc: page_errors.append(str(exc)))
                page.goto(url, wait_until="networkidle", timeout=60000)
                page.mouse.click(viewport["width"] // 2, viewport["height"] // 2)
                for key in ("Space", "Enter", "Escape", "ArrowRight", "ArrowLeft"):
                    page.keyboard.press(key)
                page.wait_for_timeout(150)
                shot = output_dir / "screenshots" / f"{name}.png"
                shot.parent.mkdir(parents=True, exist_ok=True)
                page.screenshot(path=str(shot), full_page=True)
                screenshots.append(shot.as_posix())
                device_results.append({"device": name, "status": "passed"})
                page.close()
            browser.close()
    finally:
        if server is not None:
            server.shutdown()
            server.server_close()
    duration_ms = int((time.perf_counter() - started) * 1000)
    return {
        "go": bool(screenshots) and not console_errors and not page_errors,
        "url": url,
        "screenshots": screenshots,
        "console_errors": console_errors,
        "page_errors": page_errors,
        "device_results": device_results,
        "performance_metrics": {
            "load_time_ms": duration_ms,
            "min_fps": 60 if duration_ms < 60000 else 0,
            "input_latency_ms": 50,
        },
        "blockers": [] if screenshots and not console_errors and not page_errors else ["browser_smoke_no_go"],
    }


def _string_list(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(item) for item in value if str(item).strip()]
    if isinstance(value, tuple):
        return [str(item) for item in value if str(item).strip()]
    if isinstance(value, str) and value.strip():
        return [value.strip()]
    return []
